### PR TITLE
chore(spelling): of GameTest and other words

### PR DESCRIPTION
**Pull request by jrcarl624**
In the Microsoft docs and in game gametest is spelled liked GameTest. Also fixed one or two spelling errors.
image
image

### CODE REVIEW

**Comment by jrcarl624** [comment]
Just to save you some time, the failed check was the result of a http error.

**Comment by nobu-sh** [comment]
A lot of these changes are very unnecessary and also change things that are not meant to be change.
EG: `framework -> API` we don't provide the GameTest API we provide a framework/wrapper.

It also appears you are changing a lot of our workflows. Those are as intended and do not require changes.
Also a lot of spacing changes... which do not appear to abide by our linter.

I would prefer if you would not change our workflows and leave wording as is. I will accept spelling errors, however.

**Comment by jrcarl624** [comment]
I really don't know what messed with the workflows, my vs code settings seemed to mess with the formatting as I was using the linter.

**Comment by jrcarl624** [comment]
I really don't know what messed with the workflows

**Comment by jrcarl624** [comment]
I plan to just have a different pull

**Pull request closed without merging**
