### PR TITLE
Fixed errors and inconsistencies

### PR DESCRIPTION
**Pull request by jrcarl624**

### CODE REVIEW

**Comment by ATXLtheAxolotl** [comment]
BeAPI is currently being re-written in MCBE-Utilities:next. I don't think they're accepting any pr yet until they finish the rewrite.

**Comment by jrcarl624** [comment]
> BeAPI is currently being re-written in MCBE-Utilities:next. I don't think they're accepting any pr yet until they finish the rewrite.

It's currently stable as I have been told. I have been talking to PMK and Nobu about BeApi. As BeAPI is part of an initiative to set a standard for gametest; I'm the project lead of that within Bedrock OSS...  [Look here if interested](https://forms.gle/sFr5SjprYZeQtD5f7)

**Comment by minerj101** [comment]
> BeAPI is currently being rewritten in MCBE-Utilities:next. I don't think they're accepting any pr yet until they finish the rewrite.

It's currently stable as I have been told. I have been talking to PMK about helping out with BeApi. As BeAPI is part of an initiative to set a standard for gametest and I'm the project lead of that within Bedrock OSS...  [Look here if interested ](https://forms.gle/sFr5SjprYZeQtD5f7)

**Comment by ATXLtheAxolotl** [comment]
Yes it is stable however it's still being rewritten there and once it's done that will become the default one.

**Comment by ATXLtheAxolotl** [comment]
Wait nvm

**Pull request closed without merging**
